#pragma once
// OpenCASCADE Standard_Version stub for WASM build

#define OCC_VERSION_MAJOR 7
#define OCC_VERSION_MINOR 6
#define OCC_VERSION_MAINTENANCE 0
#define OCC_VERSION_COMPLETE "7.6.0"
#define OCC_VERSION_STRING "7.6"
#define OCC_VERSION_HEX ((OCC_VERSION_MAJOR << 16) | (OCC_VERSION_MINOR << 8) | OCC_VERSION_MAINTENANCE)
