pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp wasm/demo/index.html public/
    - cp wasm/dist/odb2kicad_wasm.mjs public/
    - cp wasm/dist/odb2kicad_wasm.wasm public/
    - cp samples/test-odb.tgz public/
  artifacts:
    paths:
      - public
  only:
    - master
    - main
